#!/usr/bin/env python3
"""
AI HOT 双轨 PDF 新闻推送机器人
- --mode interval：每 2 小时抓取过去 2 小时的 AI 动态
- --mode daily：抓取当天 AI 日报
- 生成精美中文 PDF 供邮件发送
"""

import os
import sys
import argparse
import logging
from datetime import datetime, timedelta, timezone
from typing import List, Dict, Any

import requests
from weasyprint import HTML

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

# ====== 常量 ======

AIHOT_BASE = "https://aihot.virxact.com"
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/124.0.0.0 Safari/537.36 aihot-skill/0.2.0"
)

CATEGORY_LABEL = {
    "ai-models": "模型发布/更新",
    "ai-products": "产品发布/更新",
    "industry": "行业动态",
    "paper": "论文研究",
    "tip": "技巧与观点",
}

BJT = timezone(timedelta(hours=8))
PDF_FILENAME = "AI_Report.pdf"

# ====== API 获取 ======


def fetch_interval() -> List[Dict[str, Any]]:
    """获取过去 2 小时的全部 AI 动态"""
    since = (datetime.now(timezone.utc) - timedelta(hours=2)).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )
    url = f"{AIHOT_BASE}/api/public/items?mode=all&since={since}&take=100"
    logger.info("请求 interval API: %s", url)
    resp = requests.get(url, headers={"User-Agent": UA}, timeout=15)
    resp.raise_for_status()
    items = resp.json().get("items", [])
    logger.info("获取到 %d 条动态", len(items))
    return items


def fetch_daily() -> Dict[str, Any]:
    """获取当天 AI 日报（北京 08:00 还未生成时自动降级到昨天）"""
    url = f"{AIHOT_BASE}/api/public/daily"
    logger.info("请求 daily API: %s", url)
    resp = requests.get(url, headers={"User-Agent": UA}, timeout=15)
    if resp.status_code == 404:
        yesterday = (datetime.now(timezone.utc) - timedelta(days=1)).strftime("%Y-%m-%d")
        fallback = f"{AIHOT_BASE}/api/public/daily/{yesterday}"
        logger.warning("当日日报尚未生成，降级到: %s", fallback)
        resp = requests.get(fallback, headers={"User-Agent": UA}, timeout=15)
    resp.raise_for_status()
    data = resp.json()
    logger.info(
        "日报日期: %s, 板块: %d, 快讯: %d",
        data.get("date"),
        len(data.get("sections", [])),
        len(data.get("flashes", [])),
    )
    return data


# ====== 时间格式化 ======


def fmt_time(iso: str) -> str:
    """ISO 8601 UTC → 北京时间短格式"""
    if not iso:
        return ""
    try:
        dt = datetime.fromisoformat(iso.replace("Z", "+00:00"))
        return dt.astimezone(BJT).strftime("%m/%d %H:%M")
    except Exception:
        return iso


# ====== HTML → PDF ======

HTML_HEAD = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<style>
  @page { size: A4; margin: 18mm 14mm; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Noto Sans SC', 'Noto Sans CJK SC', 'WenQuanYi Micro Hei', sans-serif;
    font-size: 10.5pt; line-height: 1.8; color: #1e1e2a;
  }
  .header {
    background: linear-gradient(135deg, #0b1830 0%, #132347 50%, #0d2b55 100%);
    color: #fff; padding: 28px 36px; border-radius: 6px; margin-bottom: 22px;
  }
  .header h1 { font-size: 22pt; font-weight: 700; letter-spacing: 1px; }
  .header .meta { font-size: 9.5pt; opacity: .82; margin-top: 6px; }
  .lead {
    background: #f0f4fe; border-left: 4px solid #0b1830;
    padding: 12px 16px; margin-bottom: 20px;
    font-size: 10pt; line-height: 1.7; color: #2a2a3e;
  }
  .section-title {
    font-size: 13pt; font-weight: 700; color: #0b1830;
    border-bottom: 2px solid #0b1830; padding-bottom: 3px;
    margin-top: 18px; margin-bottom: 10px;
  }
  .card {
    background: #f7f9fc; border: 1px solid #e4e9f0;
    border-radius: 5px; padding: 10px 14px; margin-bottom: 7px;
    page-break-inside: avoid;
  }
  .card-title { font-size: 11pt; font-weight: 600; color: #0b1830; margin-bottom: 2px; }
  .card-title a { color: #0b1830; text-decoration: none; }
  .card-meta { font-size: 8.5pt; color: #7a7a8a; margin-bottom: 4px; }
  .card-summary { font-size: 9.5pt; color: #3a3a4e; line-height: 1.7; }
  .flash-item {
    font-size: 9.5pt; color: #3a3a4e;
    padding: 4px 0; border-bottom: 1px dashed #e4e9f0;
  }
  .empty { color: #999; font-size: 10pt; padding: 12px 0; }
  .footer {
    margin-top: 24px; padding-top: 10px;
    border-top: 1px solid #d0d5dd; text-align: center;
    font-size: 8.5pt; color: #999;
  }
</style>
</head>
<body>
"""

HTML_TAIL = """<div class="footer">
  Generated by <strong>AI HOT</strong> &nbsp;·&nbsp; aihot.virxact.com &nbsp;·&nbsp;
  本报告由机器人自动生成
</div>
</body>
</html>"""


def _build_cards(items: List[Dict], *, show_cat_label: bool = False) -> str:
    """构建一组卡片 HTML"""
    html = ""
    for it in items:
        title = it.get("title") or "无标题"
        url = it.get("url") or it.get("sourceUrl", "")
        source = it.get("source") or it.get("sourceName", "")
        summary = it.get("summary", "") or ""
        published = fmt_time(it.get("publishedAt", ""))
        cat = it.get("category", "")
        meta_parts = [s for s in [source, published, CATEGORY_LABEL.get(cat, "")] if s]
        meta = " · ".join(meta_parts) if meta_parts else ""
        html += f"""<div class="card">
<div class="card-title"><a href="{url}">{title}</a></div>
<div class="card-meta">{meta}</div>
<div class="card-summary">{summary}</div>
</div>
"""
    return html


def generate_pdf_interval(items: List[Dict[str, Any]]) -> str:
    """生成 interval 模式 PDF"""
    now = datetime.now(BJT)
    ts = now.strftime("%Y-%m-%d %H:%M")
    total = len(items)

    # 按 category 分组
    grouped: Dict[str, list] = {}
    for it in items:
        cat = it.get("category") or "uncategorized"
        grouped.setdefault(cat, []).append(it)

    body = ""
    for cat, cat_items in grouped.items():
        label = CATEGORY_LABEL.get(cat, cat)
        body += f'<div class="section-title">{label}（{len(cat_items)}）</div>\n'
        body += _build_cards(cat_items)

    if not body:
        body = '<div class="empty">⏳ 过去 2 小时内暂无新动态</div>'

    html = (
        HTML_HEAD
        + f"""<div class="header">
<h1>🤖 AI HOT · 动态速报</h1>
<div class="meta">{ts} 更新 · 过去 2 小时 · 共 {total} 条</div>
</div>
{body}"""
        + HTML_TAIL
    )

    HTML(string=html).write_pdf(PDF_FILENAME)
    logger.info("PDF 已生成: %s", PDF_FILENAME)
    return PDF_FILENAME


def generate_pdf_daily(data: Dict[str, Any]) -> str:
    """生成 daily 模式 PDF"""
    date_str = data.get("date", "")
    lead = data.get("lead", {})
    sections = data.get("sections", [])
    flashes = data.get("flashes", [])

    lead_html = ""
    if lead and lead.get("leadParagraph"):
        lead_html = f'<div class="lead">{lead["leadParagraph"]}</div>'

    body = ""
    for sec in sections:
        label = sec.get("label", "")
        items = sec.get("items", [])
        body += f'<div class="section-title">{label}（{len(items)}）</div>\n'
        body += _build_cards(items, show_cat_label=False)

    if flashes:
        body += '<div class="section-title">快讯（{len(flashes)}）</div>\n'
        for f in flashes:
            t = f.get("title", "")
            s = f.get("sourceName", "")
            t_meta = fmt_time(f.get("publishedAt", ""))
            body += f'<div class="flash-item">• {t} — {s}　{t_meta}</div>\n'

    if not body:
        body = '<div class="empty">暂无日报内容</div>'

    html = (
        HTML_HEAD
        + f"""<div class="header">
<h1>📰 AI HOT · AI 日报</h1>
<div class="meta">{date_str}</div>
</div>
{lead_html}
{body}"""
        + HTML_TAIL
    )

    HTML(string=html).write_pdf(PDF_FILENAME)
    logger.info("PDF 已生成: %s", PDF_FILENAME)
    return PDF_FILENAME


# ====== 主入口 ======


def main():
    parser = argparse.ArgumentParser(description="AI HOT PDF 新闻推送")
    parser.add_argument(
        "--mode",
        required=True,
        choices=["interval", "daily"],
        help="interval=每2小时动态 / daily=日报",
    )
    args = parser.parse_args()

    logger.info("=" * 50)
    logger.info("  🤖 AI HOT 双轨 PDF 推送 → mode=%s", args.mode)
    logger.info("=" * 50)

    if args.mode == "interval":
        items = fetch_interval()
        generate_pdf_interval(items)
    else:
        data = fetch_daily()
        generate_pdf_daily(data)

    logger.info("✅ 完成，输出文件: %s", PDF_FILENAME)


if __name__ == "__main__":
    main()
